### ISSUE TITLE
Add "include *" from views in DSL to JSON

### ISSUE THREAD

**Issue by ICEMANno1** [structurizr/json#4]
Hi @simonbrowndotje and first of all thanks for all your effort with Diagrams as code & the C4 model. 

I recognized while converting the DSL to JSON, the definition of "include *" in the views of the DSL files gets transformed as "real includes" in the JSON file. Can we somehow preserve this "include *" in the JSON schema, so we don't lose this information?

Thanks,
Dominik

**Comment by simonbrowndotje** [comment]
Thanks! What are you hoping to achieve by doing this?

**Comment by ICEMANno1** [comment]
Idea is to have a central model + views defined and they can be reused ("!ref") in several workspaces.

This model is partially extended by users and partially extended by automation. For the automation, we need to transform it to JSON, extend it and transform it back to DSL.

I hope this helped 😅

**Comment by simonbrowndotje** [comment]
I would avoid/not recommend transforming a JSON workspace back to the DSL because it's a lossy process ... much like reverse-engineering compiled code to source code. As you've seen, `include *` is one example, but there are several others such as implied relationships.

**Comment by ICEMANno1** [comment]
Not the reply I hoped for 😅 But you're the expert.

Nevertheless, what I'm trying to achieve:
- Have a central model and views which can be reused by several teams
- This central model should be generated by my custom tooling (e.g. mapping Terraform information into depolyment environments)
- Teams can then extend and overwrite generated model content

Since I like working better with the DSL than JSON, I'd like to let my colleagues use the DSL. 

Is there a way to parse the DSL, add content with my custom tooling and save it as DSL again? I couldn't find any SDK/Tooling for it 😅

Thanks for all your input already!

**Comment by ICEMANno1** [comment]
Ok, just to make sure I understood it right:
- central model ist generated by tooling and stored as JSON
- anything done by users can be via extending a workspace with the generated JSON file

Did I understand this right?

**Comment by simonbrowndotje** [comment]
That's correct, yes.

**Comment by ICEMANno1** [comment]
So far it worked! Thanks for the input! I'll close this issue. Have a nice weekend!
