### ISSUE TITLE
DefaultTags missing in OpenAPI

### ISSUE THREAD

**Issue by ICEMANno1** [structurizr/json#5]
Hey Simon, I just did see the attribute "default tags" in the JSON generated by structurizr/lite. Is this maybe missing in the OpenAPI document and how does this attribute behave? Thanks, Dominik

**Comment by simonbrowndotje** [comment]
They were not supposed to be there -> [https://github.com/structurizr/java/commit/ae1da0f94b8e5beb3ee6f0f0485fb2b68a7f5d77](https://github.com/structurizr/java/commit/ae1da0f94b8e5beb3ee6f0f0485fb2b68a7f5d77). 😂

**Comment by ICEMANno1** [comment]
😅 happens. I'll ignore them then.
